/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import kcl.uk.dzh.zpl.raceGame.Addition;
import kcl.uk.dzh.zpl.raceGame.AllowRestartMenu;
import kcl.uk.dzh.zpl.raceGame.EndGameBehaviour;
import kcl.uk.dzh.zpl.raceGame.FieldSpecification;
import kcl.uk.dzh.zpl.raceGame.IntLiteral;
import kcl.uk.dzh.zpl.raceGame.IntVarExpression;
import kcl.uk.dzh.zpl.raceGame.Multiplication;
import kcl.uk.dzh.zpl.raceGame.Obstaclepecification;
import kcl.uk.dzh.zpl.raceGame.RaceGame;
import kcl.uk.dzh.zpl.raceGame.RaceGamePackage;
import kcl.uk.dzh.zpl.raceGame.RealLiteral;
import kcl.uk.dzh.zpl.raceGame.ScreenSpecification;
import kcl.uk.dzh.zpl.raceGame.StartFieldDeclaration;
import kcl.uk.dzh.zpl.raceGame.SuperModeDeclaration;
import kcl.uk.dzh.zpl.raceGame.VariableDeclaration;
import kcl.uk.dzh.zpl.raceGame.WallObstacle;
import kcl.uk.dzh.zpl.raceGame.WaterObstacle;
import kcl.uk.dzh.zpl.services.RaceGameGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class RaceGameSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private RaceGameGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == RaceGamePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case RaceGamePackage.ADDITION:
				sequence_Addition(context, (Addition) semanticObject); 
				return; 
			case RaceGamePackage.ALLOW_RESTART_MENU:
				sequence_AllowRestartMenu(context, (AllowRestartMenu) semanticObject); 
				return; 
			case RaceGamePackage.END_GAME_BEHAVIOUR:
				sequence_EndGameBehaviour(context, (EndGameBehaviour) semanticObject); 
				return; 
			case RaceGamePackage.FIELD_SPECIFICATION:
				sequence_FieldSpecification(context, (FieldSpecification) semanticObject); 
				return; 
			case RaceGamePackage.INT_LITERAL:
				sequence_IntLiteral(context, (IntLiteral) semanticObject); 
				return; 
			case RaceGamePackage.INT_VAR_EXPRESSION:
				sequence_IntVarExpression(context, (IntVarExpression) semanticObject); 
				return; 
			case RaceGamePackage.MULTIPLICATION:
				sequence_Multiplication(context, (Multiplication) semanticObject); 
				return; 
			case RaceGamePackage.OBSTACLEPECIFICATION:
				sequence_Obstaclepecification(context, (Obstaclepecification) semanticObject); 
				return; 
			case RaceGamePackage.RACE_GAME:
				sequence_RaceGame(context, (RaceGame) semanticObject); 
				return; 
			case RaceGamePackage.REAL_LITERAL:
				sequence_RealLiteral(context, (RealLiteral) semanticObject); 
				return; 
			case RaceGamePackage.SCREEN_SPECIFICATION:
				sequence_ScreenSpecification(context, (ScreenSpecification) semanticObject); 
				return; 
			case RaceGamePackage.START_FIELD_DECLARATION:
				sequence_StartFieldDeclaration(context, (StartFieldDeclaration) semanticObject); 
				return; 
			case RaceGamePackage.SUPER_MODE_DECLARATION:
				sequence_SuperModeDeclaration(context, (SuperModeDeclaration) semanticObject); 
				return; 
			case RaceGamePackage.VARIABLE_DECLARATION:
				sequence_VariableDeclaration(context, (VariableDeclaration) semanticObject); 
				return; 
			case RaceGamePackage.WALL_OBSTACLE:
				sequence_WallObstacle(context, (WallObstacle) semanticObject); 
				return; 
			case RaceGamePackage.WATER_OBSTACLE:
				sequence_WaterObstacle(context, (WaterObstacle) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns Addition
	 *     Addition.Addition_1_0 returns Addition
	 *     Multiplication returns Addition
	 *     Multiplication.Multiplication_1_0 returns Addition
	 *     Primary returns Addition
	 *
	 * Constraint:
	 *     (left=Addition_Addition_1_0 (operator+='+' | operator+='-') right+=Multiplication)
	 * </pre>
	 */
	protected void sequence_Addition(ISerializationContext context, Addition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OptionSpecification returns AllowRestartMenu
	 *     AllowRestartMenu returns AllowRestartMenu
	 *
	 * Constraint:
	 *     {AllowRestartMenu}
	 * </pre>
	 */
	protected void sequence_AllowRestartMenu(ISerializationContext context, AllowRestartMenu semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EndGameBehaviour returns EndGameBehaviour
	 *     OptionSpecification returns EndGameBehaviour
	 *
	 * Constraint:
	 *     (win=STRING lost=STRING)
	 * </pre>
	 */
	protected void sequence_EndGameBehaviour(ISerializationContext context, EndGameBehaviour semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.END_GAME_BEHAVIOUR__WIN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.END_GAME_BEHAVIOUR__WIN));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.END_GAME_BEHAVIOUR__LOST) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.END_GAME_BEHAVIOUR__LOST));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEndGameBehaviourAccess().getWinSTRINGTerminalRuleCall_2_0(), semanticObject.getWin());
		feeder.accept(grammarAccess.getEndGameBehaviourAccess().getLostSTRINGTerminalRuleCall_4_0(), semanticObject.getLost());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FieldSpecification returns FieldSpecification
	 *
	 * Constraint:
	 *     (name=ID enemyCount=Addition obstacle=Obstaclepecification nextLevel=[FieldSpecification|ID])
	 * </pre>
	 */
	protected void sequence_FieldSpecification(ISerializationContext context, FieldSpecification semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.FIELD_SPECIFICATION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.FIELD_SPECIFICATION__NAME));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.FIELD_SPECIFICATION__ENEMY_COUNT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.FIELD_SPECIFICATION__ENEMY_COUNT));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.FIELD_SPECIFICATION__OBSTACLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.FIELD_SPECIFICATION__OBSTACLE));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.FIELD_SPECIFICATION__NEXT_LEVEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.FIELD_SPECIFICATION__NEXT_LEVEL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFieldSpecificationAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getFieldSpecificationAccess().getEnemyCountAdditionParserRuleCall_5_0(), semanticObject.getEnemyCount());
		feeder.accept(grammarAccess.getFieldSpecificationAccess().getObstacleObstaclepecificationParserRuleCall_6_0(), semanticObject.getObstacle());
		feeder.accept(grammarAccess.getFieldSpecificationAccess().getNextLevelFieldSpecificationIDTerminalRuleCall_9_0_1(), semanticObject.eGet(RaceGamePackage.Literals.FIELD_SPECIFICATION__NEXT_LEVEL, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns IntLiteral
	 *     Addition.Addition_1_0 returns IntLiteral
	 *     Multiplication returns IntLiteral
	 *     Multiplication.Multiplication_1_0 returns IntLiteral
	 *     Primary returns IntLiteral
	 *     IntLiteral returns IntLiteral
	 *
	 * Constraint:
	 *     val=INT
	 * </pre>
	 */
	protected void sequence_IntLiteral(ISerializationContext context, IntLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.INT_LITERAL__VAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.INT_LITERAL__VAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntLiteralAccess().getValINTTerminalRuleCall_0(), semanticObject.getVal());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns IntVarExpression
	 *     Addition.Addition_1_0 returns IntVarExpression
	 *     Multiplication returns IntVarExpression
	 *     Multiplication.Multiplication_1_0 returns IntVarExpression
	 *     Primary returns IntVarExpression
	 *     IntVarExpression returns IntVarExpression
	 *
	 * Constraint:
	 *     var=[VariableDeclaration|ID]
	 * </pre>
	 */
	protected void sequence_IntVarExpression(ISerializationContext context, IntVarExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.INT_VAR_EXPRESSION__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.INT_VAR_EXPRESSION__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntVarExpressionAccess().getVarVariableDeclarationIDTerminalRuleCall_0_1(), semanticObject.eGet(RaceGamePackage.Literals.INT_VAR_EXPRESSION__VAR, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns Multiplication
	 *     Addition.Addition_1_0 returns Multiplication
	 *     Multiplication returns Multiplication
	 *     Multiplication.Multiplication_1_0 returns Multiplication
	 *     Primary returns Multiplication
	 *
	 * Constraint:
	 *     (left=Multiplication_Multiplication_1_0 (operator+='*' | operator+='/') right+=Primary)
	 * </pre>
	 */
	protected void sequence_Multiplication(ISerializationContext context, Multiplication semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Obstaclepecification returns Obstaclepecification
	 *
	 * Constraint:
	 *     (name=ID fields+=ObstacleMember*)
	 * </pre>
	 */
	protected void sequence_Obstaclepecification(ISerializationContext context, Obstaclepecification semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RaceGame returns RaceGame
	 *
	 * Constraint:
	 *     (name=ID variable+=VariableDeclaration? screen=ScreenSpecification fields+=FieldSpecification+ options+=OptionSpecification+)
	 * </pre>
	 */
	protected void sequence_RaceGame(ISerializationContext context, RaceGame semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns RealLiteral
	 *     Addition.Addition_1_0 returns RealLiteral
	 *     Multiplication returns RealLiteral
	 *     Multiplication.Multiplication_1_0 returns RealLiteral
	 *     Primary returns RealLiteral
	 *     RealLiteral returns RealLiteral
	 *
	 * Constraint:
	 *     val=REAL
	 * </pre>
	 */
	protected void sequence_RealLiteral(ISerializationContext context, RealLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.REAL_LITERAL__VAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.REAL_LITERAL__VAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRealLiteralAccess().getValREALParserRuleCall_0(), semanticObject.getVal());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ScreenSpecification returns ScreenSpecification
	 *
	 * Constraint:
	 *     (name=ID screenWidth=INT screenHeight=INT)
	 * </pre>
	 */
	protected void sequence_ScreenSpecification(ISerializationContext context, ScreenSpecification semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.SCREEN_SPECIFICATION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.SCREEN_SPECIFICATION__NAME));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.SCREEN_SPECIFICATION__SCREEN_WIDTH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.SCREEN_SPECIFICATION__SCREEN_WIDTH));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.SCREEN_SPECIFICATION__SCREEN_HEIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.SCREEN_SPECIFICATION__SCREEN_HEIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getScreenSpecificationAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getScreenSpecificationAccess().getScreenWidthINTTerminalRuleCall_5_0(), semanticObject.getScreenWidth());
		feeder.accept(grammarAccess.getScreenSpecificationAccess().getScreenHeightINTTerminalRuleCall_8_0(), semanticObject.getScreenHeight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OptionSpecification returns StartFieldDeclaration
	 *     StartFieldDeclaration returns StartFieldDeclaration
	 *
	 * Constraint:
	 *     field=[FieldSpecification|ID]
	 * </pre>
	 */
	protected void sequence_StartFieldDeclaration(ISerializationContext context, StartFieldDeclaration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.START_FIELD_DECLARATION__FIELD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.START_FIELD_DECLARATION__FIELD));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStartFieldDeclarationAccess().getFieldFieldSpecificationIDTerminalRuleCall_2_0_1(), semanticObject.eGet(RaceGamePackage.Literals.START_FIELD_DECLARATION__FIELD, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OptionSpecification returns SuperModeDeclaration
	 *     SuperModeDeclaration returns SuperModeDeclaration
	 *
	 * Constraint:
	 *     {SuperModeDeclaration}
	 * </pre>
	 */
	protected void sequence_SuperModeDeclaration(ISerializationContext context, SuperModeDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     VariableDeclaration returns VariableDeclaration
	 *
	 * Constraint:
	 *     (name=ID value=INT)
	 * </pre>
	 */
	protected void sequence_VariableDeclaration(ISerializationContext context, VariableDeclaration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.VARIABLE_DECLARATION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.VARIABLE_DECLARATION__NAME));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.VARIABLE_DECLARATION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.VARIABLE_DECLARATION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableDeclarationAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getVariableDeclarationAccess().getValueINTTerminalRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ObstacleMember returns WallObstacle
	 *     WallObstacle returns WallObstacle
	 *
	 * Constraint:
	 *     (name=ID wallWidth=INT wallHeight=INT wallPosX=INT wallPosY=INT)
	 * </pre>
	 */
	protected void sequence_WallObstacle(ISerializationContext context, WallObstacle semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.OBSTACLE_MEMBER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.OBSTACLE_MEMBER__NAME));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.WALL_OBSTACLE__WALL_WIDTH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.WALL_OBSTACLE__WALL_WIDTH));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.WALL_OBSTACLE__WALL_HEIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.WALL_OBSTACLE__WALL_HEIGHT));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.WALL_OBSTACLE__WALL_POS_X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.WALL_OBSTACLE__WALL_POS_X));
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.WALL_OBSTACLE__WALL_POS_Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.WALL_OBSTACLE__WALL_POS_Y));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWallObstacleAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getWallObstacleAccess().getWallWidthINTTerminalRuleCall_5_0(), semanticObject.getWallWidth());
		feeder.accept(grammarAccess.getWallObstacleAccess().getWallHeightINTTerminalRuleCall_8_0(), semanticObject.getWallHeight());
		feeder.accept(grammarAccess.getWallObstacleAccess().getWallPosXINTTerminalRuleCall_11_0(), semanticObject.getWallPosX());
		feeder.accept(grammarAccess.getWallObstacleAccess().getWallPosYINTTerminalRuleCall_14_0(), semanticObject.getWallPosY());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ObstacleMember returns WaterObstacle
	 *     WaterObstacle returns WaterObstacle
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_WaterObstacle(ISerializationContext context, WaterObstacle semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, RaceGamePackage.Literals.OBSTACLE_MEMBER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, RaceGamePackage.Literals.OBSTACLE_MEMBER__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWaterObstacleAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
