/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame.impl;

import kcl.uk.dzh.zpl.raceGame.AllowRestartMenu;
import kcl.uk.dzh.zpl.raceGame.RaceGamePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Allow Restart Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AllowRestartMenuImpl extends OptionSpecificationImpl implements AllowRestartMenu
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AllowRestartMenuImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RaceGamePackage.Literals.ALLOW_RESTART_MENU;
  }

} //AllowRestartMenuImpl
