/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame.impl;

import kcl.uk.dzh.zpl.raceGame.Expression;
import kcl.uk.dzh.zpl.raceGame.FieldSpecification;
import kcl.uk.dzh.zpl.raceGame.Obstaclepecification;
import kcl.uk.dzh.zpl.raceGame.RaceGamePackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Field Specification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.impl.FieldSpecificationImpl#getName <em>Name</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.impl.FieldSpecificationImpl#getEnemyCount <em>Enemy Count</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.impl.FieldSpecificationImpl#getObstacle <em>Obstacle</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.impl.FieldSpecificationImpl#getNextLevel <em>Next Level</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FieldSpecificationImpl extends MinimalEObjectImpl.Container implements FieldSpecification
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEnemyCount() <em>Enemy Count</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnemyCount()
   * @generated
   * @ordered
   */
  protected Expression enemyCount;

  /**
   * The cached value of the '{@link #getObstacle() <em>Obstacle</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObstacle()
   * @generated
   * @ordered
   */
  protected Obstaclepecification obstacle;

  /**
   * The cached value of the '{@link #getNextLevel() <em>Next Level</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNextLevel()
   * @generated
   * @ordered
   */
  protected FieldSpecification nextLevel;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FieldSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RaceGamePackage.Literals.FIELD_SPECIFICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RaceGamePackage.FIELD_SPECIFICATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getEnemyCount()
  {
    return enemyCount;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnemyCount(Expression newEnemyCount, NotificationChain msgs)
  {
    Expression oldEnemyCount = enemyCount;
    enemyCount = newEnemyCount;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT, oldEnemyCount, newEnemyCount);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnemyCount(Expression newEnemyCount)
  {
    if (newEnemyCount != enemyCount)
    {
      NotificationChain msgs = null;
      if (enemyCount != null)
        msgs = ((InternalEObject)enemyCount).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT, null, msgs);
      if (newEnemyCount != null)
        msgs = ((InternalEObject)newEnemyCount).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT, null, msgs);
      msgs = basicSetEnemyCount(newEnemyCount, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT, newEnemyCount, newEnemyCount));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Obstaclepecification getObstacle()
  {
    return obstacle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetObstacle(Obstaclepecification newObstacle, NotificationChain msgs)
  {
    Obstaclepecification oldObstacle = obstacle;
    obstacle = newObstacle;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE, oldObstacle, newObstacle);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObstacle(Obstaclepecification newObstacle)
  {
    if (newObstacle != obstacle)
    {
      NotificationChain msgs = null;
      if (obstacle != null)
        msgs = ((InternalEObject)obstacle).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE, null, msgs);
      if (newObstacle != null)
        msgs = ((InternalEObject)newObstacle).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE, null, msgs);
      msgs = basicSetObstacle(newObstacle, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE, newObstacle, newObstacle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FieldSpecification getNextLevel()
  {
    if (nextLevel != null && nextLevel.eIsProxy())
    {
      InternalEObject oldNextLevel = (InternalEObject)nextLevel;
      nextLevel = (FieldSpecification)eResolveProxy(oldNextLevel);
      if (nextLevel != oldNextLevel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RaceGamePackage.FIELD_SPECIFICATION__NEXT_LEVEL, oldNextLevel, nextLevel));
      }
    }
    return nextLevel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FieldSpecification basicGetNextLevel()
  {
    return nextLevel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNextLevel(FieldSpecification newNextLevel)
  {
    FieldSpecification oldNextLevel = nextLevel;
    nextLevel = newNextLevel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RaceGamePackage.FIELD_SPECIFICATION__NEXT_LEVEL, oldNextLevel, nextLevel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT:
        return basicSetEnemyCount(null, msgs);
      case RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE:
        return basicSetObstacle(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RaceGamePackage.FIELD_SPECIFICATION__NAME:
        return getName();
      case RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT:
        return getEnemyCount();
      case RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE:
        return getObstacle();
      case RaceGamePackage.FIELD_SPECIFICATION__NEXT_LEVEL:
        if (resolve) return getNextLevel();
        return basicGetNextLevel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RaceGamePackage.FIELD_SPECIFICATION__NAME:
        setName((String)newValue);
        return;
      case RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT:
        setEnemyCount((Expression)newValue);
        return;
      case RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE:
        setObstacle((Obstaclepecification)newValue);
        return;
      case RaceGamePackage.FIELD_SPECIFICATION__NEXT_LEVEL:
        setNextLevel((FieldSpecification)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RaceGamePackage.FIELD_SPECIFICATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT:
        setEnemyCount((Expression)null);
        return;
      case RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE:
        setObstacle((Obstaclepecification)null);
        return;
      case RaceGamePackage.FIELD_SPECIFICATION__NEXT_LEVEL:
        setNextLevel((FieldSpecification)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RaceGamePackage.FIELD_SPECIFICATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RaceGamePackage.FIELD_SPECIFICATION__ENEMY_COUNT:
        return enemyCount != null;
      case RaceGamePackage.FIELD_SPECIFICATION__OBSTACLE:
        return obstacle != null;
      case RaceGamePackage.FIELD_SPECIFICATION__NEXT_LEVEL:
        return nextLevel != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //FieldSpecificationImpl
