/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame.impl;

import kcl.uk.dzh.zpl.raceGame.OptionSpecification;
import kcl.uk.dzh.zpl.raceGame.RaceGamePackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Option Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OptionSpecificationImpl extends MinimalEObjectImpl.Container implements OptionSpecification
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OptionSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RaceGamePackage.Literals.OPTION_SPECIFICATION;
  }

} //OptionSpecificationImpl
