/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame.impl;

import kcl.uk.dzh.zpl.raceGame.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class RaceGameFactoryImpl extends EFactoryImpl implements RaceGameFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static RaceGameFactory init()
  {
    try
    {
      RaceGameFactory theRaceGameFactory = (RaceGameFactory)EPackage.Registry.INSTANCE.getEFactory(RaceGamePackage.eNS_URI);
      if (theRaceGameFactory != null)
      {
        return theRaceGameFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new RaceGameFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RaceGameFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case RaceGamePackage.RACE_GAME: return createRaceGame();
      case RaceGamePackage.VARIABLE_DECLARATION: return createVariableDeclaration();
      case RaceGamePackage.END_GAME_BEHAVIOUR: return createEndGameBehaviour();
      case RaceGamePackage.SCREEN_SPECIFICATION: return createScreenSpecification();
      case RaceGamePackage.OBSTACLEPECIFICATION: return createObstaclepecification();
      case RaceGamePackage.OBSTACLE_MEMBER: return createObstacleMember();
      case RaceGamePackage.WATER_OBSTACLE: return createWaterObstacle();
      case RaceGamePackage.WALL_OBSTACLE: return createWallObstacle();
      case RaceGamePackage.FIELD_SPECIFICATION: return createFieldSpecification();
      case RaceGamePackage.OPTION_SPECIFICATION: return createOptionSpecification();
      case RaceGamePackage.SUPER_MODE_DECLARATION: return createSuperModeDeclaration();
      case RaceGamePackage.START_FIELD_DECLARATION: return createStartFieldDeclaration();
      case RaceGamePackage.ALLOW_RESTART_MENU: return createAllowRestartMenu();
      case RaceGamePackage.EXPRESSION: return createExpression();
      case RaceGamePackage.INT_VAR_EXPRESSION: return createIntVarExpression();
      case RaceGamePackage.INT_LITERAL: return createIntLiteral();
      case RaceGamePackage.REAL_LITERAL: return createRealLiteral();
      case RaceGamePackage.ADDITION: return createAddition();
      case RaceGamePackage.MULTIPLICATION: return createMultiplication();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RaceGame createRaceGame()
  {
    RaceGameImpl raceGame = new RaceGameImpl();
    return raceGame;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableDeclaration createVariableDeclaration()
  {
    VariableDeclarationImpl variableDeclaration = new VariableDeclarationImpl();
    return variableDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EndGameBehaviour createEndGameBehaviour()
  {
    EndGameBehaviourImpl endGameBehaviour = new EndGameBehaviourImpl();
    return endGameBehaviour;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ScreenSpecification createScreenSpecification()
  {
    ScreenSpecificationImpl screenSpecification = new ScreenSpecificationImpl();
    return screenSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Obstaclepecification createObstaclepecification()
  {
    ObstaclepecificationImpl obstaclepecification = new ObstaclepecificationImpl();
    return obstaclepecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ObstacleMember createObstacleMember()
  {
    ObstacleMemberImpl obstacleMember = new ObstacleMemberImpl();
    return obstacleMember;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WaterObstacle createWaterObstacle()
  {
    WaterObstacleImpl waterObstacle = new WaterObstacleImpl();
    return waterObstacle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WallObstacle createWallObstacle()
  {
    WallObstacleImpl wallObstacle = new WallObstacleImpl();
    return wallObstacle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FieldSpecification createFieldSpecification()
  {
    FieldSpecificationImpl fieldSpecification = new FieldSpecificationImpl();
    return fieldSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OptionSpecification createOptionSpecification()
  {
    OptionSpecificationImpl optionSpecification = new OptionSpecificationImpl();
    return optionSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SuperModeDeclaration createSuperModeDeclaration()
  {
    SuperModeDeclarationImpl superModeDeclaration = new SuperModeDeclarationImpl();
    return superModeDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StartFieldDeclaration createStartFieldDeclaration()
  {
    StartFieldDeclarationImpl startFieldDeclaration = new StartFieldDeclarationImpl();
    return startFieldDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AllowRestartMenu createAllowRestartMenu()
  {
    AllowRestartMenuImpl allowRestartMenu = new AllowRestartMenuImpl();
    return allowRestartMenu;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression createExpression()
  {
    ExpressionImpl expression = new ExpressionImpl();
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntVarExpression createIntVarExpression()
  {
    IntVarExpressionImpl intVarExpression = new IntVarExpressionImpl();
    return intVarExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntLiteral createIntLiteral()
  {
    IntLiteralImpl intLiteral = new IntLiteralImpl();
    return intLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RealLiteral createRealLiteral()
  {
    RealLiteralImpl realLiteral = new RealLiteralImpl();
    return realLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Addition createAddition()
  {
    AdditionImpl addition = new AdditionImpl();
    return addition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Multiplication createMultiplication()
  {
    MultiplicationImpl multiplication = new MultiplicationImpl();
    return multiplication;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RaceGamePackage getRaceGamePackage()
  {
    return (RaceGamePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static RaceGamePackage getPackage()
  {
    return RaceGamePackage.eINSTANCE;
  }

} //RaceGameFactoryImpl
