/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame.impl;

import kcl.uk.dzh.zpl.raceGame.RaceGamePackage;
import kcl.uk.dzh.zpl.raceGame.SuperModeDeclaration;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Super Mode Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SuperModeDeclarationImpl extends OptionSpecificationImpl implements SuperModeDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuperModeDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RaceGamePackage.Literals.SUPER_MODE_DECLARATION;
  }

} //SuperModeDeclarationImpl
