/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RaceGameUiModule extends AbstractRaceGameUiModule {

	public RaceGameUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
