/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Allow Restart Menu</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getAllowRestartMenu()
 * @model
 * @generated
 */
public interface AllowRestartMenu extends OptionSpecification
{
} // AllowRestartMenu
