/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
