/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.IntLiteral#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getIntLiteral()
 * @model
 * @generated
 */
public interface IntLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(int)
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getIntLiteral_Val()
   * @model
   * @generated
   */
  int getVal();

  /**
   * Sets the value of the '{@link kcl.uk.dzh.zpl.raceGame.IntLiteral#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(int value);

} // IntLiteral
