/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Obstaclepecification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.Obstaclepecification#getName <em>Name</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.Obstaclepecification#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getObstaclepecification()
 * @model
 * @generated
 */
public interface Obstaclepecification extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getObstaclepecification_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link kcl.uk.dzh.zpl.raceGame.Obstaclepecification#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link kcl.uk.dzh.zpl.raceGame.ObstacleMember}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getObstaclepecification_Fields()
   * @model containment="true"
   * @generated
   */
  EList<ObstacleMember> getFields();

} // Obstaclepecification
