/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see kcl.uk.dzh.zpl.raceGame.RaceGameFactory
 * @model kind="package"
 * @generated
 */
public interface RaceGamePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "raceGame";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.uk.kcl/dzh/zpl/RaceGame";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "raceGame";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RaceGamePackage eINSTANCE = kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl.init();

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.RaceGameImpl <em>Race Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGameImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getRaceGame()
   * @generated
   */
  int RACE_GAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RACE_GAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RACE_GAME__VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Screen</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RACE_GAME__SCREEN = 2;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RACE_GAME__FIELDS = 3;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RACE_GAME__OPTIONS = 4;

  /**
   * The number of structural features of the '<em>Race Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RACE_GAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.VariableDeclarationImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.OptionSpecificationImpl <em>Option Specification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.OptionSpecificationImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getOptionSpecification()
   * @generated
   */
  int OPTION_SPECIFICATION = 9;

  /**
   * The number of structural features of the '<em>Option Specification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_SPECIFICATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.EndGameBehaviourImpl <em>End Game Behaviour</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.EndGameBehaviourImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getEndGameBehaviour()
   * @generated
   */
  int END_GAME_BEHAVIOUR = 2;

  /**
   * The feature id for the '<em><b>Win</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_GAME_BEHAVIOUR__WIN = OPTION_SPECIFICATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Lost</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_GAME_BEHAVIOUR__LOST = OPTION_SPECIFICATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>End Game Behaviour</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_GAME_BEHAVIOUR_FEATURE_COUNT = OPTION_SPECIFICATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.ScreenSpecificationImpl <em>Screen Specification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.ScreenSpecificationImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getScreenSpecification()
   * @generated
   */
  int SCREEN_SPECIFICATION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCREEN_SPECIFICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Screen Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCREEN_SPECIFICATION__SCREEN_WIDTH = 1;

  /**
   * The feature id for the '<em><b>Screen Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCREEN_SPECIFICATION__SCREEN_HEIGHT = 2;

  /**
   * The number of structural features of the '<em>Screen Specification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCREEN_SPECIFICATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.ObstaclepecificationImpl <em>Obstaclepecification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.ObstaclepecificationImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getObstaclepecification()
   * @generated
   */
  int OBSTACLEPECIFICATION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLEPECIFICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLEPECIFICATION__FIELDS = 1;

  /**
   * The number of structural features of the '<em>Obstaclepecification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLEPECIFICATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.ObstacleMemberImpl <em>Obstacle Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.ObstacleMemberImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getObstacleMember()
   * @generated
   */
  int OBSTACLE_MEMBER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE_MEMBER__NAME = 0;

  /**
   * The number of structural features of the '<em>Obstacle Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBSTACLE_MEMBER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.WaterObstacleImpl <em>Water Obstacle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.WaterObstacleImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getWaterObstacle()
   * @generated
   */
  int WATER_OBSTACLE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_OBSTACLE__NAME = OBSTACLE_MEMBER__NAME;

  /**
   * The number of structural features of the '<em>Water Obstacle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_OBSTACLE_FEATURE_COUNT = OBSTACLE_MEMBER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.WallObstacleImpl <em>Wall Obstacle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.WallObstacleImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getWallObstacle()
   * @generated
   */
  int WALL_OBSTACLE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL_OBSTACLE__NAME = OBSTACLE_MEMBER__NAME;

  /**
   * The feature id for the '<em><b>Wall Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL_OBSTACLE__WALL_WIDTH = OBSTACLE_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Wall Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL_OBSTACLE__WALL_HEIGHT = OBSTACLE_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Wall Pos X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL_OBSTACLE__WALL_POS_X = OBSTACLE_MEMBER_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Wall Pos Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL_OBSTACLE__WALL_POS_Y = OBSTACLE_MEMBER_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Wall Obstacle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALL_OBSTACLE_FEATURE_COUNT = OBSTACLE_MEMBER_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.FieldSpecificationImpl <em>Field Specification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.FieldSpecificationImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getFieldSpecification()
   * @generated
   */
  int FIELD_SPECIFICATION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_SPECIFICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Enemy Count</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_SPECIFICATION__ENEMY_COUNT = 1;

  /**
   * The feature id for the '<em><b>Obstacle</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_SPECIFICATION__OBSTACLE = 2;

  /**
   * The feature id for the '<em><b>Next Level</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_SPECIFICATION__NEXT_LEVEL = 3;

  /**
   * The number of structural features of the '<em>Field Specification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_SPECIFICATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.SuperModeDeclarationImpl <em>Super Mode Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.SuperModeDeclarationImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getSuperModeDeclaration()
   * @generated
   */
  int SUPER_MODE_DECLARATION = 10;

  /**
   * The number of structural features of the '<em>Super Mode Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_MODE_DECLARATION_FEATURE_COUNT = OPTION_SPECIFICATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.StartFieldDeclarationImpl <em>Start Field Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.StartFieldDeclarationImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getStartFieldDeclaration()
   * @generated
   */
  int START_FIELD_DECLARATION = 11;

  /**
   * The feature id for the '<em><b>Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_FIELD_DECLARATION__FIELD = OPTION_SPECIFICATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Start Field Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_FIELD_DECLARATION_FEATURE_COUNT = OPTION_SPECIFICATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.AllowRestartMenuImpl <em>Allow Restart Menu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.AllowRestartMenuImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getAllowRestartMenu()
   * @generated
   */
  int ALLOW_RESTART_MENU = 12;

  /**
   * The number of structural features of the '<em>Allow Restart Menu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALLOW_RESTART_MENU_FEATURE_COUNT = OPTION_SPECIFICATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.ExpressionImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 13;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.IntVarExpressionImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 14;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.IntLiteralImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 15;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.RealLiteralImpl <em>Real Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.RealLiteralImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getRealLiteral()
   * @generated
   */
  int REAL_LITERAL = 16;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Real Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.AdditionImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link kcl.uk.dzh.zpl.raceGame.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see kcl.uk.dzh.zpl.raceGame.impl.MultiplicationImpl
   * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.RaceGame <em>Race Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Race Game</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGame
   * @generated
   */
  EClass getRaceGame();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGame#getName()
   * @see #getRaceGame()
   * @generated
   */
  EAttribute getRaceGame_Name();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variable</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGame#getVariable()
   * @see #getRaceGame()
   * @generated
   */
  EReference getRaceGame_Variable();

  /**
   * Returns the meta object for the containment reference '{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getScreen <em>Screen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Screen</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGame#getScreen()
   * @see #getRaceGame()
   * @generated
   */
  EReference getRaceGame_Screen();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGame#getFields()
   * @see #getRaceGame()
   * @generated
   */
  EReference getRaceGame_Fields();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGame#getOptions()
   * @see #getRaceGame()
   * @generated
   */
  EReference getRaceGame_Options();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.EndGameBehaviour <em>End Game Behaviour</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End Game Behaviour</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.EndGameBehaviour
   * @generated
   */
  EClass getEndGameBehaviour();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.EndGameBehaviour#getWin <em>Win</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Win</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.EndGameBehaviour#getWin()
   * @see #getEndGameBehaviour()
   * @generated
   */
  EAttribute getEndGameBehaviour_Win();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.EndGameBehaviour#getLost <em>Lost</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lost</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.EndGameBehaviour#getLost()
   * @see #getEndGameBehaviour()
   * @generated
   */
  EAttribute getEndGameBehaviour_Lost();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification <em>Screen Specification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Screen Specification</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.ScreenSpecification
   * @generated
   */
  EClass getScreenSpecification();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getName()
   * @see #getScreenSpecification()
   * @generated
   */
  EAttribute getScreenSpecification_Name();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getScreenWidth <em>Screen Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Screen Width</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getScreenWidth()
   * @see #getScreenSpecification()
   * @generated
   */
  EAttribute getScreenSpecification_ScreenWidth();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getScreenHeight <em>Screen Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Screen Height</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getScreenHeight()
   * @see #getScreenSpecification()
   * @generated
   */
  EAttribute getScreenSpecification_ScreenHeight();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.Obstaclepecification <em>Obstaclepecification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obstaclepecification</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Obstaclepecification
   * @generated
   */
  EClass getObstaclepecification();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.Obstaclepecification#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Obstaclepecification#getName()
   * @see #getObstaclepecification()
   * @generated
   */
  EAttribute getObstaclepecification_Name();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.uk.dzh.zpl.raceGame.Obstaclepecification#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Obstaclepecification#getFields()
   * @see #getObstaclepecification()
   * @generated
   */
  EReference getObstaclepecification_Fields();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.ObstacleMember <em>Obstacle Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Obstacle Member</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.ObstacleMember
   * @generated
   */
  EClass getObstacleMember();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.ObstacleMember#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.ObstacleMember#getName()
   * @see #getObstacleMember()
   * @generated
   */
  EAttribute getObstacleMember_Name();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.WaterObstacle <em>Water Obstacle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Water Obstacle</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.WaterObstacle
   * @generated
   */
  EClass getWaterObstacle();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.WallObstacle <em>Wall Obstacle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wall Obstacle</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.WallObstacle
   * @generated
   */
  EClass getWallObstacle();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.WallObstacle#getWallWidth <em>Wall Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wall Width</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.WallObstacle#getWallWidth()
   * @see #getWallObstacle()
   * @generated
   */
  EAttribute getWallObstacle_WallWidth();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.WallObstacle#getWallHeight <em>Wall Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wall Height</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.WallObstacle#getWallHeight()
   * @see #getWallObstacle()
   * @generated
   */
  EAttribute getWallObstacle_WallHeight();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.WallObstacle#getWallPosX <em>Wall Pos X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wall Pos X</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.WallObstacle#getWallPosX()
   * @see #getWallObstacle()
   * @generated
   */
  EAttribute getWallObstacle_WallPosX();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.WallObstacle#getWallPosY <em>Wall Pos Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wall Pos Y</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.WallObstacle#getWallPosY()
   * @see #getWallObstacle()
   * @generated
   */
  EAttribute getWallObstacle_WallPosY();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.FieldSpecification <em>Field Specification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field Specification</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.FieldSpecification
   * @generated
   */
  EClass getFieldSpecification();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.FieldSpecification#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.FieldSpecification#getName()
   * @see #getFieldSpecification()
   * @generated
   */
  EAttribute getFieldSpecification_Name();

  /**
   * Returns the meta object for the containment reference '{@link kcl.uk.dzh.zpl.raceGame.FieldSpecification#getEnemyCount <em>Enemy Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Enemy Count</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.FieldSpecification#getEnemyCount()
   * @see #getFieldSpecification()
   * @generated
   */
  EReference getFieldSpecification_EnemyCount();

  /**
   * Returns the meta object for the containment reference '{@link kcl.uk.dzh.zpl.raceGame.FieldSpecification#getObstacle <em>Obstacle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obstacle</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.FieldSpecification#getObstacle()
   * @see #getFieldSpecification()
   * @generated
   */
  EReference getFieldSpecification_Obstacle();

  /**
   * Returns the meta object for the reference '{@link kcl.uk.dzh.zpl.raceGame.FieldSpecification#getNextLevel <em>Next Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Next Level</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.FieldSpecification#getNextLevel()
   * @see #getFieldSpecification()
   * @generated
   */
  EReference getFieldSpecification_NextLevel();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.OptionSpecification <em>Option Specification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option Specification</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.OptionSpecification
   * @generated
   */
  EClass getOptionSpecification();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.SuperModeDeclaration <em>Super Mode Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Super Mode Declaration</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.SuperModeDeclaration
   * @generated
   */
  EClass getSuperModeDeclaration();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.StartFieldDeclaration <em>Start Field Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start Field Declaration</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.StartFieldDeclaration
   * @generated
   */
  EClass getStartFieldDeclaration();

  /**
   * Returns the meta object for the reference '{@link kcl.uk.dzh.zpl.raceGame.StartFieldDeclaration#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Field</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.StartFieldDeclaration#getField()
   * @see #getStartFieldDeclaration()
   * @generated
   */
  EReference getStartFieldDeclaration_Field();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.AllowRestartMenu <em>Allow Restart Menu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Allow Restart Menu</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.AllowRestartMenu
   * @generated
   */
  EClass getAllowRestartMenu();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link kcl.uk.dzh.zpl.raceGame.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.RealLiteral <em>Real Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Literal</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.RealLiteral
   * @generated
   */
  EClass getRealLiteral();

  /**
   * Returns the meta object for the attribute '{@link kcl.uk.dzh.zpl.raceGame.RealLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.RealLiteral#getVal()
   * @see #getRealLiteral()
   * @generated
   */
  EAttribute getRealLiteral_Val();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link kcl.uk.dzh.zpl.raceGame.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link kcl.uk.dzh.zpl.raceGame.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.uk.dzh.zpl.raceGame.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link kcl.uk.dzh.zpl.raceGame.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link kcl.uk.dzh.zpl.raceGame.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link kcl.uk.dzh.zpl.raceGame.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link kcl.uk.dzh.zpl.raceGame.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see kcl.uk.dzh.zpl.raceGame.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RaceGameFactory getRaceGameFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.RaceGameImpl <em>Race Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGameImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getRaceGame()
     * @generated
     */
    EClass RACE_GAME = eINSTANCE.getRaceGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RACE_GAME__NAME = eINSTANCE.getRaceGame_Name();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RACE_GAME__VARIABLE = eINSTANCE.getRaceGame_Variable();

    /**
     * The meta object literal for the '<em><b>Screen</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RACE_GAME__SCREEN = eINSTANCE.getRaceGame_Screen();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RACE_GAME__FIELDS = eINSTANCE.getRaceGame_Fields();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RACE_GAME__OPTIONS = eINSTANCE.getRaceGame_Options();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.VariableDeclarationImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.EndGameBehaviourImpl <em>End Game Behaviour</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.EndGameBehaviourImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getEndGameBehaviour()
     * @generated
     */
    EClass END_GAME_BEHAVIOUR = eINSTANCE.getEndGameBehaviour();

    /**
     * The meta object literal for the '<em><b>Win</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute END_GAME_BEHAVIOUR__WIN = eINSTANCE.getEndGameBehaviour_Win();

    /**
     * The meta object literal for the '<em><b>Lost</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute END_GAME_BEHAVIOUR__LOST = eINSTANCE.getEndGameBehaviour_Lost();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.ScreenSpecificationImpl <em>Screen Specification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.ScreenSpecificationImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getScreenSpecification()
     * @generated
     */
    EClass SCREEN_SPECIFICATION = eINSTANCE.getScreenSpecification();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCREEN_SPECIFICATION__NAME = eINSTANCE.getScreenSpecification_Name();

    /**
     * The meta object literal for the '<em><b>Screen Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCREEN_SPECIFICATION__SCREEN_WIDTH = eINSTANCE.getScreenSpecification_ScreenWidth();

    /**
     * The meta object literal for the '<em><b>Screen Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCREEN_SPECIFICATION__SCREEN_HEIGHT = eINSTANCE.getScreenSpecification_ScreenHeight();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.ObstaclepecificationImpl <em>Obstaclepecification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.ObstaclepecificationImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getObstaclepecification()
     * @generated
     */
    EClass OBSTACLEPECIFICATION = eINSTANCE.getObstaclepecification();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBSTACLEPECIFICATION__NAME = eINSTANCE.getObstaclepecification_Name();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBSTACLEPECIFICATION__FIELDS = eINSTANCE.getObstaclepecification_Fields();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.ObstacleMemberImpl <em>Obstacle Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.ObstacleMemberImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getObstacleMember()
     * @generated
     */
    EClass OBSTACLE_MEMBER = eINSTANCE.getObstacleMember();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBSTACLE_MEMBER__NAME = eINSTANCE.getObstacleMember_Name();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.WaterObstacleImpl <em>Water Obstacle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.WaterObstacleImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getWaterObstacle()
     * @generated
     */
    EClass WATER_OBSTACLE = eINSTANCE.getWaterObstacle();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.WallObstacleImpl <em>Wall Obstacle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.WallObstacleImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getWallObstacle()
     * @generated
     */
    EClass WALL_OBSTACLE = eINSTANCE.getWallObstacle();

    /**
     * The meta object literal for the '<em><b>Wall Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WALL_OBSTACLE__WALL_WIDTH = eINSTANCE.getWallObstacle_WallWidth();

    /**
     * The meta object literal for the '<em><b>Wall Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WALL_OBSTACLE__WALL_HEIGHT = eINSTANCE.getWallObstacle_WallHeight();

    /**
     * The meta object literal for the '<em><b>Wall Pos X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WALL_OBSTACLE__WALL_POS_X = eINSTANCE.getWallObstacle_WallPosX();

    /**
     * The meta object literal for the '<em><b>Wall Pos Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WALL_OBSTACLE__WALL_POS_Y = eINSTANCE.getWallObstacle_WallPosY();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.FieldSpecificationImpl <em>Field Specification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.FieldSpecificationImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getFieldSpecification()
     * @generated
     */
    EClass FIELD_SPECIFICATION = eINSTANCE.getFieldSpecification();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD_SPECIFICATION__NAME = eINSTANCE.getFieldSpecification_Name();

    /**
     * The meta object literal for the '<em><b>Enemy Count</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD_SPECIFICATION__ENEMY_COUNT = eINSTANCE.getFieldSpecification_EnemyCount();

    /**
     * The meta object literal for the '<em><b>Obstacle</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD_SPECIFICATION__OBSTACLE = eINSTANCE.getFieldSpecification_Obstacle();

    /**
     * The meta object literal for the '<em><b>Next Level</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD_SPECIFICATION__NEXT_LEVEL = eINSTANCE.getFieldSpecification_NextLevel();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.OptionSpecificationImpl <em>Option Specification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.OptionSpecificationImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getOptionSpecification()
     * @generated
     */
    EClass OPTION_SPECIFICATION = eINSTANCE.getOptionSpecification();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.SuperModeDeclarationImpl <em>Super Mode Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.SuperModeDeclarationImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getSuperModeDeclaration()
     * @generated
     */
    EClass SUPER_MODE_DECLARATION = eINSTANCE.getSuperModeDeclaration();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.StartFieldDeclarationImpl <em>Start Field Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.StartFieldDeclarationImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getStartFieldDeclaration()
     * @generated
     */
    EClass START_FIELD_DECLARATION = eINSTANCE.getStartFieldDeclaration();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START_FIELD_DECLARATION__FIELD = eINSTANCE.getStartFieldDeclaration_Field();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.AllowRestartMenuImpl <em>Allow Restart Menu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.AllowRestartMenuImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getAllowRestartMenu()
     * @generated
     */
    EClass ALLOW_RESTART_MENU = eINSTANCE.getAllowRestartMenu();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.ExpressionImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.IntVarExpressionImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.IntLiteralImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.RealLiteralImpl <em>Real Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.RealLiteralImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getRealLiteral()
     * @generated
     */
    EClass REAL_LITERAL = eINSTANCE.getRealLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REAL_LITERAL__VAL = eINSTANCE.getRealLiteral_Val();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.AdditionImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link kcl.uk.dzh.zpl.raceGame.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see kcl.uk.dzh.zpl.raceGame.impl.MultiplicationImpl
     * @see kcl.uk.dzh.zpl.raceGame.impl.RaceGamePackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

  }

} //RaceGamePackage
