/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Race Game</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getName <em>Name</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getVariable <em>Variable</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getScreen <em>Screen</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getFields <em>Fields</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getRaceGame()
 * @model
 * @generated
 */
public interface RaceGame extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getRaceGame_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference list.
   * The list contents are of type {@link kcl.uk.dzh.zpl.raceGame.VariableDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference list.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getRaceGame_Variable()
   * @model containment="true"
   * @generated
   */
  EList<VariableDeclaration> getVariable();

  /**
   * Returns the value of the '<em><b>Screen</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Screen</em>' containment reference.
   * @see #setScreen(ScreenSpecification)
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getRaceGame_Screen()
   * @model containment="true"
   * @generated
   */
  ScreenSpecification getScreen();

  /**
   * Sets the value of the '{@link kcl.uk.dzh.zpl.raceGame.RaceGame#getScreen <em>Screen</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Screen</em>' containment reference.
   * @see #getScreen()
   * @generated
   */
  void setScreen(ScreenSpecification value);

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link kcl.uk.dzh.zpl.raceGame.FieldSpecification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getRaceGame_Fields()
   * @model containment="true"
   * @generated
   */
  EList<FieldSpecification> getFields();

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference list.
   * The list contents are of type {@link kcl.uk.dzh.zpl.raceGame.OptionSpecification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference list.
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getRaceGame_Options()
   * @model containment="true"
   * @generated
   */
  EList<OptionSpecification> getOptions();

} // RaceGame
