/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.RealLiteral#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getRealLiteral()
 * @model
 * @generated
 */
public interface RealLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(float)
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getRealLiteral_Val()
   * @model
   * @generated
   */
  float getVal();

  /**
   * Sets the value of the '{@link kcl.uk.dzh.zpl.raceGame.RealLiteral#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(float value);

} // RealLiteral
