/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Screen Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getName <em>Name</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getScreenWidth <em>Screen Width</em>}</li>
 *   <li>{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getScreenHeight <em>Screen Height</em>}</li>
 * </ul>
 *
 * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getScreenSpecification()
 * @model
 * @generated
 */
public interface ScreenSpecification extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getScreenSpecification_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Screen Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Screen Width</em>' attribute.
   * @see #setScreenWidth(int)
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getScreenSpecification_ScreenWidth()
   * @model
   * @generated
   */
  int getScreenWidth();

  /**
   * Sets the value of the '{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getScreenWidth <em>Screen Width</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Screen Width</em>' attribute.
   * @see #getScreenWidth()
   * @generated
   */
  void setScreenWidth(int value);

  /**
   * Returns the value of the '<em><b>Screen Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Screen Height</em>' attribute.
   * @see #setScreenHeight(int)
   * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getScreenSpecification_ScreenHeight()
   * @model
   * @generated
   */
  int getScreenHeight();

  /**
   * Sets the value of the '{@link kcl.uk.dzh.zpl.raceGame.ScreenSpecification#getScreenHeight <em>Screen Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Screen Height</em>' attribute.
   * @see #getScreenHeight()
   * @generated
   */
  void setScreenHeight(int value);

} // ScreenSpecification
