/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.raceGame;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Water Obstacle</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see kcl.uk.dzh.zpl.raceGame.RaceGamePackage#getWaterObstacle()
 * @model
 * @generated
 */
public interface WaterObstacle extends ObstacleMember
{
} // WaterObstacle
