/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kcl.uk.dzh.zpl.RaceGameRuntimeModule;
import kcl.uk.dzh.zpl.RaceGameStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RaceGameIdeSetup extends RaceGameStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RaceGameRuntimeModule(), new RaceGameIdeModule()));
	}
	
}
