/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RaceGameAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("kcl/uk/dzh/zpl/parser/antlr/internal/InternalRaceGame.tokens");
	}
}
