/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.parser.antlr;

import com.google.inject.Inject;
import kcl.uk.dzh.zpl.parser.antlr.internal.InternalRaceGameParser;
import kcl.uk.dzh.zpl.services.RaceGameGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RaceGameParser extends AbstractAntlrParser {

	@Inject
	private RaceGameGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRaceGameParser createParser(XtextTokenStream stream) {
		return new InternalRaceGameParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RaceGame";
	}

	public RaceGameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RaceGameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
