/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RaceGameStandaloneSetup extends RaceGameStandaloneSetupGenerated {

	public static void doSetup() {
		new RaceGameStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
