/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.validation;

import org.eclipse.xtext.validation.Check;

import kcl.uk.dzh.zpl.raceGame.RaceGamePackage;
import kcl.uk.dzh.zpl.raceGame.ScreenSpecification;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all") 
public class RaceGameValidator extends AbstractRaceGameValidator {
		
	public static final String INVALID_SCREEN_WIDTH = "screenWidth";
	public static final String INVALID_SCREEN_HEIGHT = "screenHeight";
	public static final String INVALID_SCREEN_COMPARE = "screenCompare";

	
	@Check 
	public void checkScreenSpecification(ScreenSpecification screenSpecification) {
		if (screenSpecification.getScreenWidth() < 700 || screenSpecification.getScreenWidth() > 800) {
			error("Screen width can't lower 700 or higher 800",
				null, INVALID_SCREEN_WIDTH);
		}
		if (screenSpecification.getScreenHeight() < 700 || screenSpecification.getScreenHeight() > 800) {
			error("Screen height can't lower 700 or higher 800",
					null, INVALID_SCREEN_HEIGHT);
		}
		if (screenSpecification.getScreenWidth() < screenSpecification.getScreenHeight()) {
			warning("Screen width must higher than height ", 
					null, INVALID_SCREEN_COMPARE);
		}
	}
}
