/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.ui.tests;

import com.google.inject.Injector;
import kcl.uk.dzh.zpl.RaceGame.ui.internal.RaceGameActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RaceGameUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RaceGameActivator.getInstance().getInjector("kcl.uk.dzh.zpl.RaceGame");
	}

}
