/*
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRaceGameScopeProvider extends DelegatingScopeProvider {
}
