/**
 * generated by Xtext 2.26.0
 */
package kcl.uk.dzh.zpl.generator;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class GetResultGenerator {
  public GetResultGenerator(final GetResultGenerator mpp) {
  }
  
  public CharSequence generateFrame() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package run;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import javax.swing.JLabel;");
    _builder.newLine();
    _builder.append("import javax.swing.JRadioButton;");
    _builder.newLine();
    _builder.append("import javax.swing.JTextField;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class GetResult {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("JRadioButton jr_mans[];");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("JTextField jtf_cost;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("JLabel jl_money;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("JRadioButton selected;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public GetResult(GameJFrame gj) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("jr_mans = gj.jr_mans;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("jtf_cost = gj.jtf_cost;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("jl_money = gj.jl_money;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.selected = gj.selected;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("//计算钱数");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public int getRightMoney(){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int cost = Integer.valueOf(jtf_cost.getText());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int money = Integer.valueOf(jl_money.getText());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for(JRadioButton jr : jr_mans){");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if(selected.getText().equals(RunningMan.NO1.name)){");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("return money + cost;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return money - cost; ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("//把新出炉的钱数设置在界面上");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setMoney(){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("//先计算钱数 再进行清空操作-----------------");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("jl_money.setText(getRightMoney()+ \"\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("jtf_cost.setText(\"\");");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
}
